services:
  price-pusher:
    # Use this to build the price pusher from source.
    #
    # Please note that the docker build from source only works in x86_64 platforms
    # and doesn't work on arm platforms (like Apple M1/M2).
    #
    # build:
    #   context: ../..
    #   dockerfile: Dockerfile.node
    #   args:
    #     package: "@pythnetwork/price-pusher"

    # Replace <version> with the latest released image of the price pusher from here:
    # https://gallery.ecr.aws/pyth-network/xc-price-pusher
    image: public.ecr.aws/pyth-network/xc-price-pusher:v8.1.0
    restart: always
    command:
      - "npm"
      - "run"
      - "start"
      - "--"
      - "fuel"
      - "--endpoint"
      # Replace this with RPC endpoint URL for the EVM network.
      - "https://mainnet.fuel.network/v1/graphql"
      - "--private-key-file"
      - "/mnemonic.txt"
      # Replace this with the address of the Pyth contract on the EVM network.
      - "--pyth-contract-address"
      - "0x1c86fdd9e0e7bc0d2ae1bf6817ef4834ffa7247655701ee1b031b52a24c523da"
      - "--price-service-endpoint"
      - "https://hermes.pyth.network" # Replace this with a private Hermes RPC for more reliability
      - "--price-config-file"
      - "/price-config.stable.sample.yaml"
    configs:
      - mnemonic
      - price_config
    volumes:
      - ./price-config.stable.sample.yaml:/price-config.stable.sample.yaml
      - ./mnemonic.txt:/mnemonic.txt
configs:
  mnemonic:
    file: mnemonic.txt # Replace this with the path to the mnemonic file
  price_config:
    file: price-config.stable.sample.yaml # Replace this with the path to the price configuration file
